# Generated by Django 5.0.4 on 2024-04-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20240421_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='feature_product',
            new_name='featured_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_first_n_8f83e0_idx',
            old_name='store_custo_first_n_a7e990_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
        migrations.AlterModelTable(
            name='orderitems',
            table='store_orderitem',
        ),
    ]
